# Apps
# cask 'google-chrome'
# cask 'visual-studio-code'
cask 'affinity-designer'
cask 'affinity-photo'
cask 'alfred'
cask 'gimp'
cask 'gpg-suite'
cask 'insomnia'
cask 'iterm2'
cask 'karabiner-elements'
cask 'krisp'
cask 'loopback'
cask 'maccy'
cask 'obsidian'
cask 'rectangle'
cask 'scroll-reverser'
cask 'spotify'
cask 'vlc'
cask 'zoom'
